version: '3'

services:
  sqld-primary:
    build:
      context: .
      dockerfile: ./libsql/Dockerfile
    platform: linux/amd64
    environment:
      - SQLD_NODE=primary
      - SQLD_HTTP_LISTEN_ADDR=0.0.0.0:8000
    ports:
      - 8000:8000
